version: "3.1"

services:
  user-api:
    container_name: user-api
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: ${DOCKER_URL}
      NODE_ENV: development
      PORT: 8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres-printgo
    networks:
      - printgo_network
    command: ["sh", "-c", "npx prisma db push && yarn start"]

  postgres-printgo:
    image: postgres:13
    container_name: postgres-printgo-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: printgo-local
    ports:
      - "5445:5432"
    networks:
      - printgo_network

networks:
  printgo_network:
    name: printgo_network
    driver: bridge
    external: true